### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ChenchenZheng** [ChenchenZheng/attack_on_titan_api#16]
- [x] Title tag is set and exceeds 20 chars
- [x] Favicon tag is set
- [x] Open Graph meta tags are properly set
- [x] 404 and 500 pages are customized
